# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('stuno', models.IntegerField()),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('starttime', models.DateTimeField()),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PublishedLec', to='enroll.Acmer')),
                ('members', models.ManyToManyField(related_name='PaticipatedLec', to='enroll.Acmer')),
            ],
        ),
    ]
