# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('starttime', models.DateTimeField()),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PublishedLec', to='enroll.Acmer')),
                ('members', models.ManyToManyField(related_name='PaticipatedLec', to='enroll.Acmer')),
            ],
        ),
    ]
